name: Daily Link Runner

on:
  workflow_dispatch:  # 👈 Enables the "Run workflow" button
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run the Python script
        run: python open_links.py
