name: Daily Link Runner

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST = 3:30 UTC
  workflow_dispatch:       # Allows manual triggering from Actions tab

jobs:
  run-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python open_links.py
