name: Run Daily Link Script

on:
  workflow_dispatch:       # Manual run
  schedule:
    - cron: '30 3 * * *'   # Daily at 9:00 AM IST (03:30 UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run Python script
        run: python open_links.py
