name: Run Daily Link Script

on:
  workflow_dispatch:  # lets you trigger manually
  schedule:
    - cron: '0 10 * * *'  # runs daily at 10:00 UTC (3:30 PM IST)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run open_links.py
        run: python open_links.py
